name: Docker Build & Run

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-docker-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-docker-app:latest

      - name: Run container in background
        run: docker run -d -p 5000:5000 --name my-app-container ${{ secrets.DOCKER_USERNAME }}/ci-docker-app:latest

      - name: Wait for app to be ready
        run: sleep 5

      - name: Verify container by HTTP request
        run: curl http://localhost:5000 || exit 1

      - name: Show logs for debugging
        run: docker logs my-app-container

      - name: Stop and remove container
        run: docker rm -f my-app-container
